
/**
 * TransactionService - Standardized financial engine (V4)
 */
const TransactionService = {
    TYPES: {
        INCOME: 'income',
        EXPENSE: 'expense',
        TRANSFER: 'transfer',
        ALLOCATION: 'project_allocation',
        PAYMENT: 'payment',    // Link to Workers/Participants
        PURCHASE: 'purchase',  // Link to Materials/Stock
        REVENUE: 'revenue',    // Generated by project
        WITHDRAWAL: 'withdrawal',
        REFUND: 'refund'
    },

    /**
     * Add a unique transaction record
     */
    add(data) {
        const now = new Date().toISOString();
        const tx = {
            id: uid(),
            projectId: data.projectId || null,
            type: data.type || this.TYPES.EXPENSE,
            amount: parseFloat(data.amount) || 0,
            currency: data.currency || state.mainCurrency,
            date: data.date || now,
            month: data.month || String(data.date || now).slice(0, 7),
            category: data.category || "Autre",
            description: data.description || "",
            sourceModule: data.sourceModule || null, // e.g., 'workers', 'materials'
            sourceItemId: data.sourceItemId || null, // ID of the specific worker/material
            createdAt: now,
            updatedAt: now
        };

        state.transactions.push(tx);
        return tx;
    },

    delete(id) {
        const tx = state.transactions.find(t => t.id === id);
        if (!tx) return false;

        // If it's a project allocation, cleanup assignments
        if (tx.type === this.TYPES.ALLOCATION) {
            const key = Object.keys(state.monthlyAssignments).find(k => state.monthlyAssignments[k].transactionId === id);
            if (key) {
                state.monthlyAssignments[key].checked = false;
                state.monthlyAssignments[key].transactionId = null;
            }
        }

        // Integrity check: if linked to generic data (like a worker), the UI should reflect the change
        // RelationService will handle the logical link during rendering.
        state.transactions = state.transactions.filter(t => t.id !== id);
        return true;
    },

    /**
     * Search and Filter
     */
    getByProject(projectId, filters = {}) {
        let results = state.transactions.filter(t => t.projectId === projectId);
        if (filters.type) results = results.filter(t => t.type === filters.type);
        if (filters.sourceModule) results = results.filter(t => t.sourceModule === filters.sourceModule);
        if (filters.sourceItemId) results = results.filter(t => t.sourceItemId === filters.sourceItemId);

        return results.sort((a, b) => new Date(b.date) - new Date(a.date));
    }
};
